---
- name: setup a vprofile bastion host
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:

    - name: Import VPC setup variables
      include_vars: ./vars/vpc_setup

    - name: Import vpc variable
      include_vars: vars/vpc-output_vars

    - name: Create vprofile ec2 key
      ec2_key:
        name: vprofile-key
        region: "{{region}}"
      register: key_out

    - name: Save private key into a file bastion-key.pem
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed

    - name: Create Security group for bastion host
      ec2_group:
        name: Bastion-host-sg
        description: Allow port 22 from everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
      register: BastionSG_out

    - name: Creating Bastion Host
      amazon.aws.ec2_instance:
        key_name: vprofile-key
        region: "{{ region }}"
        instance_type: t2.micro
        image_id: "{{ bastion_ami }}"
        wait: yes
        wait_timeout: 300
        vpc_subnet_id: "{{ pubsub1id }}"
        security_groups:
          - "{{ BastionSG_out.group_id }}"  # Corrected parameter
        exact_count: 1  # Correcting usage, remove count_tag
        tags: # Use tags instead of instance_tags
          Name: "Bastion_host"
          Project: Vprofile
          Owner: DevOps_Team
      register: bastionHost_out

    - name: Insert/Update "BastionSGid" in vars/vpc-output_vars
      blockinfile:
        path: vars/vpc-output_vars
        backup: yes
        block:
          BastionSGid: {{BastionSG_out.group_id}}
