- name: Genrate artifact, copy artifact & sql file to files directory
  host: localhost
  connection: local
  become: yes
  tasks:
    - name: Install jdk, maven, git
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - git
        - openjdk-8-jdk
        - maven
    - name: Clone source code from github
      git:
        repo: 'https://github.com/devopshydclub/vprofile-project.git'
        dest: ./Vprofile-repo
        version: vp-ren
      register: git_status

    - name: mvn install command to build artifact
      command: "mvn install"
      args:
        chdir: Vprofile-repo
      when: git_status.changed
      register: mvn_info

    - name: Copy artifacts to files directory
      copy:
        scr: "{{item}}"
        dest: files/ROOT.war
      with_fileglob: Vprofile-repo/target/*.war

    - name: Copy SQL file to files directory
      copy:
        scr: Vprofile-repo/src/main/resources/db_backup.sql
        dest: files/db_backup.sql
    # - name: Copy artifacts to files directory
    #command: "cp Vprofile-repo/target/Vprofile-v2.war files"

    #- name: Copy SQL file to files directory
    #command: "cp Vprofile-repo/src/main/resources/db_backup.sql files"